services:
  pest:
    build: .
    volumes:
      - .:/app
      - pest_node_modules:/app/node_modules
      - pest_vendor:/app/vendor
    environment:
      - APP_ENV=testing
      - XDEBUG_MODE=off
    working_dir: /app

volumes:
  pest_node_modules:
  pest_vendor:
