services:
  pest:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
      - /app/vendor
    environment:
      - APP_ENV=testing
      - XDEBUG_MODE=off
      - DISPLAY=:99
    working_dir: /app
    entrypoint: ["./vendor/bin/pest"]
