name: Tests

on: [push, pull_request]

jobs:
  feature-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.3, 8.4]

    name: PHP ${{ matrix.php }}

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
      - run: composer install --no-interaction --prefer-dist --optimize-autoloader
      - run: composer phpcs
      - run: ./vendor/bin/pest tests/Feature/ --ci

  browser-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: none
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: composer install --no-interaction --prefer-dist --optimize-autoloader
      - run: npm install
      - run: npx playwright install chromium --with-deps
      - run: ./vendor/bin/pest tests/Browser/ --ci
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-screenshots
          path: ./tests/Browser/Screenshots/
          retention-days: 7
